name: pick_date_time_package
description: A new Flutter package project.
version: 0.0.1
author:
#homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.0
  intl: ^0.16.1
  theme_package:
    path: ../theme_package

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
